# Skript by lasse
# Version 1.2

options:
	prefix: &cInvsee &8»
	noperm: &cInvsee &8» &cDafür hast  du keine Rechte.

command /invsee [<player>]:
	permission: server.command.invsee
	permission message: {@noperm} 
	trigger:
		if arg 1 is not set:
			send "{@prefix} &cBitte gebe einen Namen an"
		else:
			send "{@prefix} &cDu hast das Inventar von &b%arg-1% &cgeöffnet"
			open the arg-1's inventory for the player
